POST http://127.0.0.1:8080/post/create HTTP/1.1
content-type: application/json

{
  "post": {
    "author": ["author_name1", "author_name2"],
    "underlabel": "underlabel_value",
    "label": "label_value",
    "text": "text_value",
    "footer": "footer_value",
    "tags": ["tag1", "tag2"]
  },
  "auth": {
    "name": "example_user",
    "password": "example_password"
  }
}

curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
     -H "Authorization: Bearer 2rcXbOcfgqcbsug1kVVKHBkl9fxDAVoX2MoMZ37K" \
     -H "Content-Type:application/json"